- tag: 'basic-hello-world:0.0.1'
  dockerfile: ./trivial

- task: vanilla-hello-world
  tags: ['hello-world', 'hello-world:latest']
  dockerfile: ./trivial

- dockerfile: ./trivial
  task: 'misctag-hello-world:basic'

- skip: true
  task: skipme

- dockerfile: ./trivial
  tag: 'misctag-hello-world:ineedbasic'
  dependsOn: [vanilla-hello-world, basic-hello-world]

- dockerfile: ./trivial
  tag: misctag-hello-world
  dependsOn: vanilla-hello-world

- dockerfile: ./trivial
  task: 'misctag-hello-world:latest'
  dependsOn: vanilla-hello-world

- dependsOn: [basic-hello-world, misctag-hello-world, vanilla-hello-world]
  tag: node:10-centos7
  dockerfile: node-test/Dockerfile
  context: ./myartifacts/
  description: 'This message shows that your installation appears to be working correctly.'
  license: MIT
  args:
    BUILD_FROM: 'node:10.13.0-alpine'

- task: second
  dependsOn: [node]
  tag: node/test-node:latest
  dockerfile: ./trivial
